// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"BillingEngine/internal/repository"
	"BillingEngine/internal/service"
)

// Injectors from wire.go:

func InitializeLoanService() (service.LoanService, error) {
	loanRepository := repository.NewInMemoryLoanRepository()
	loanService := service.NewLoanService(loanRepository)
	return loanService, nil
}
